### ISSUE TITLE
Suggestion: EMI equilvent/compat 

### ISSUE THREAD

**Issue by Shibva** [shedaniel/RoughlyEnoughResources#8]
It would be nice if this mod was able to run with EM. Its a shame that while it can run JEI plugins, the equivalent (Not Enough Resources) has not implemented back in the world analysis thing for showing modded ores and stuff

**Comment by AlphaMode** [comment]
I dont plan on making a emi version of the mod. If thats what your requesting. As far as backwards compatibility goes that's provided by rei. Honestly I'm not sure what you mean. Your issue seems to be more regarded towards REI itself and not RER
